/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Entities.Mesa;
import Dao.MesaDao;
import Models.MesaDaoImpl;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JPanel;


/**
 *
 * @author victo
 */
public class MainFormMesas extends javax.swing.JFrame {

    // private MesaUI mesa1, mesa2, mesa3, mesa4;
    
    private MesaDao mesaDao = MesaDaoImpl.getInstance();
    private Map<JButton, Mesa> mesasMap = new HashMap<>();
    private JPanel panelMesas;


    public MainFormMesas() {
        initComponents();
        setLocationRelativeTo(null);

        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestonMenuButton = new javax.swing.JButton();
        PedidosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        mesa3Button = new javax.swing.JButton();
        mesa1Button = new javax.swing.JButton();
        mesa2Button = new javax.swing.JButton();
        mesa4Button = new javax.swing.JButton();
        mesa5Button = new javax.swing.JButton();
        mesa6Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GestonMenuButton.setText("Gestion Menu");
        GestonMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestonMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GestonMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        PedidosButton.setText("Pedidos");
        PedidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PedidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Mesas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        getContentPane().add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));
        getContentPane().add(filler5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        mesa3Button.setText("Mesa 3");
        getContentPane().add(mesa3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 80, 70));

        mesa1Button.setText("Mesa 1");
        mesa1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mesa1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 70));

        mesa2Button.setText("Mesa 2");
        getContentPane().add(mesa2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 70));

        mesa4Button.setText("Mesa 4");
        getContentPane().add(mesa4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 70));

        mesa5Button.setText("Mesa 5");
        getContentPane().add(mesa5Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 80, 70));

        mesa6Button.setText("Mesa 6");
        mesa6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa6ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mesa6Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mesa1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesa1ButtonActionPerformed

    private void mesa6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa6ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesa6ButtonActionPerformed

    private void GestonMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GestonMenuButtonActionPerformed
        GestionMenu ventanaGestionMenu = new GestionMenu();
        ventanaGestionMenu.pack();
        ventanaGestionMenu.setLocationRelativeTo(this);
        ventanaGestionMenu.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_GestonMenuButtonActionPerformed

    private void PedidosButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PedidosButtonActionPerformed
        Pedidos ventanaPedidos = new Pedidos();
        ventanaPedidos.pack();
        ventanaPedidos.setLocationRelativeTo(this);
        ventanaPedidos.setVisible(true);
        this.setVisible(false);

    }// GEN-LAST:event_PedidosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormMesas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestonMenuButton;
    private javax.swing.JButton PedidosButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mesa1Button;
    private javax.swing.JButton mesa2Button;
    private javax.swing.JButton mesa3Button;
    private javax.swing.JButton mesa4Button;
    private javax.swing.JButton mesa5Button;
    private javax.swing.JButton mesa6Button;
    // End of variables declaration//GEN-END:variables
}
