/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;
import Models.Mesa;


/**
 *
 * @author victo
 */
public class MainFormMesas extends javax.swing.JFrame {

    private Mesa mesa1,mesa2,mesa3,mesa4;
    public MainFormMesas() {
        initComponents();
        
        mesa1=new Mesa("1",Mesa1Button);
        mesa2=new Mesa("2",Mesa2Button);
        mesa3=new Mesa("3",Mesa3Button);
        mesa4=new Mesa("4",Mesa4Button);
        
        mesa1.agregarProducto("Asado");
        mesa2.agregarProducto("Pizza");
        
        mesa2.agregarProducto("Helado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mesa1Button = new javax.swing.JButton();
        Mesa2Button = new javax.swing.JButton();
        Mesa3Button = new javax.swing.JButton();
        Mesa4Button = new javax.swing.JButton();
        GestonMenuButton = new javax.swing.JButton();
        PedidosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mesa1Button.setText("Mesa 1");
        getContentPane().add(Mesa1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 60));

        Mesa2Button.setText("Mesa 2");
        getContentPane().add(Mesa2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 60));

        Mesa3Button.setText("Mesa 3");
        getContentPane().add(Mesa3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 60));

        Mesa4Button.setText("Mesa 4");
        getContentPane().add(Mesa4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 60));

        GestonMenuButton.setText("Gestion Menu");
        GestonMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestonMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GestonMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        PedidosButton.setText("Pedidos");
        getContentPane().add(PedidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 110, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Mesas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestonMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestonMenuButtonActionPerformed
       GestionMenu ventanaGestionMenu = new GestionMenu();
       ventanaGestionMenu.pack();
       ventanaGestionMenu.setLocationRelativeTo(this);
       ventanaGestionMenu.setVisible(true);
       this.setVisible(false); 
    }//GEN-LAST:event_GestonMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestonMenuButton;
    private javax.swing.JButton Mesa1Button;
    private javax.swing.JButton Mesa2Button;
    private javax.swing.JButton Mesa3Button;
    private javax.swing.JButton Mesa4Button;
    private javax.swing.JButton PedidosButton;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
