/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.MesaUI;


/**
 *
 * @author victo
 */
public class MainFormMesas extends javax.swing.JFrame {

    private MesaUI mesa1,mesa2,mesa3,mesa4;
    public MainFormMesas() {
       
        initComponents();
         setLocationRelativeTo(null);
        mesa1=new MesaUI(" 1",Mesa1Button);
        mesa2=new MesaUI(" 2",Mesa2Button);
        mesa3=new MesaUI(" 3",Mesa3Button);
        mesa4=new MesaUI(" 4",Mesa4Button);
        
        mesa1.agregarProducto("Asado");
        mesa2.agregarProducto("Pizza");
        
        mesa2.agregarProducto("Helado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mesa1Button = new javax.swing.JButton();
        Mesa2Button = new javax.swing.JButton();
        Mesa3Button = new javax.swing.JButton();
        Mesa4Button = new javax.swing.JButton();
        GestonMenuButton = new javax.swing.JButton();
        PedidosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mesa1Button.setText("Mesa 1");
        getContentPane().add(Mesa1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 60));

        Mesa2Button.setText("Mesa 2");
        getContentPane().add(Mesa2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 60));

        Mesa3Button.setText("Mesa 3");
        getContentPane().add(Mesa3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 60));

        Mesa4Button.setText("Mesa 4");
        getContentPane().add(Mesa4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 60));

        GestonMenuButton.setText("Productos");
        GestonMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductos(evt);
            }
        });
        getContentPane().add(GestonMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, -1));

        PedidosButton.setText("Pedidos");
        PedidosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PedidosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 120, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Mesas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        getContentPane().add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));
        getContentPane().add(filler5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        getContentPane().add(filler6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductos
      ProductosVista ventanaProducto = new ProductosVista();
    ventanaProducto.pack();
    ventanaProducto.setLocationRelativeTo(this); // Centrada respecto a esta ventana
    ventanaProducto.setVisible(true);
    this.setVisible(false); 
    }//GEN-LAST:event_buttonProductos

    private void PedidosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosButtonActionPerformed
     Pedidos ventanaPedidos= new Pedidos();
     ventanaPedidos.pack();
     ventanaPedidos.setLocationRelativeTo(this);
     ventanaPedidos.setVisible(true);
     this.setVisible(false);
        
        
    }//GEN-LAST:event_PedidosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormMesas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestonMenuButton;
    private javax.swing.JButton Mesa1Button;
    private javax.swing.JButton Mesa2Button;
    private javax.swing.JButton Mesa3Button;
    private javax.swing.JButton Mesa4Button;
    private javax.swing.JButton PedidosButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
